updating workflows

diff --git a/ghrelease b/ghrelease
--- a/ghrelease
+++ b/ghrelease
@@ -1,5 +1,7 @@
 #!/bin/sh
 ###$_begin-include: utils/ghrelease.sh
+ashlib_version='v3.1.0'
+
 #
 # Release script
 #
@@ -48,6 +50,8 @@ stderr() {
 
 
 checks=".ghrelease-checks"
+updver=".ghrelease-versioning"
+
 rc=false
 github=false
 gh_auth=false
@@ -72,6 +76,72 @@ do
   shift
 done
 
+#@@@ ghrelease.1.md
+#@ :version: v3.1.0
+#@
+#@ # NAME
+#@
+#@ **ghrelease** -- Perform a github release
+#@
+#@ # SYNOPSIS
+#@
+#@ **ghrelease** \[_options_] _version_
+#@
+#@ # DESCRIPTION
+#@
+#@ Perform activities related to creating a new release.  It will do the
+#@ following:
+#@
+#@ 1. If a file named `.ghrelease-checks` exists it is executed.
+#@    If it returns error, the process stops.
+#@ 2. Makes sure that there are no uncommited changes.
+#@ 3. Makes sure that there are commits since previous release
+#@ 4. Collect commit messages into release notes.
+#@ 5. Creates a `version.h` or `VERSION` file with the _version_
+#@ 6. If a file named `.ghrelease-versioning` exists, it is executed.
+#@    If it returns error, the process stops.
+#@    This script is used to update files with versioning strings
+#@    that needs to be added to the commit.
+#@ 7. Commit and create a tag with _version_.
+#@ 8. Use the github API to create a new release.
+#@
+#@ This is supposed to kick off a github workflow that can create
+#@ release artifacts.
+#@
+#@ # OPTIONS
+#@
+#@ - **--\[no-]index** : Generate index data
+#@ - **--rc|-t** : Create a release candidate (test release).  Can *not*
+#@   be done on the _default_ branch.
+#@ - **--rel|-r** : Create a release.  This is the default.  Can *only*
+#@   be done on the _default_ branch.
+#@ - **--\[no-\]gh**, -g or -G : Use the github API (this is the efault)
+#@   Use `--no-gh` or `-G` to disable this.
+#@ - **-i** \[_dir_] : install **ghrelease** to current directory or _dir_.
+#@ - _version_ : version tag
+#@ - **--purge** : Delete all pre-releases
+#@ - **--test**: Run pre-release tests
+#@ - **--del|-D** _release_ : Delete _release_
+#@
+#@ # RELEASES
+#@
+#@ First to prepare a release you must start with a clean repository,
+#@ without any pending commits.  This can be either in a development
+#@ branch for pre-releases, or the default branch for actual release.
+#@ **NOTE** that development branches must have been pushed to [github](https://github.com/).
+#@
+#@ Run the `ghrelease` command with the new `version` tag.  Specify `--rc` or
+#@ `-t` for a pre-release.
+#@
+#@ A release will be created in the [github](https://github.com) repository
+#@ and if an *Github Action* is available to create release artifacts,
+#@ these will be automatically generated.
+#@
+#@ # FILES
+#@ - `.ghrelease-checks` : executable script used to do pre-release checkes
+#@ - `.ghrelease-versioning` : executable script used to update versions
+#@
+
 if [ $# -lt 1 ] ; then
   cat <<-_EOF_
 	Usage: $0 [options] version
@@ -84,7 +154,8 @@ if [ $# -lt 1 ] ; then
 	* version : version tag
 	* -i [dir] : install $0 to current directory or [dir].
 
-	If version is --purge, it will delete all pre-releases
+	If version is --purge, it will delete all pre-releases.
+	If version is --test, it will run tests.
 	_EOF_
   gh release list
   exit 1
@@ -104,9 +175,8 @@ else
 fi
 cd "$repodir"
 
-git pull --tags # Make sure remote|local tags are in sync
-
-if [ x"$relid" = x"--purge" ] ; then
+case "$relid" in
+--purge)
   # Remove pre-release versions...
   if $github ; then
     gh release list | awk '$2 == "Pre-release" { print $1 }' | while read vtag
@@ -119,7 +189,42 @@ if [ x"$relid" = x"--purge" ] ; then
     echo "You can only purge from github releases"
   fi
   exit
-fi
+  ;;
+--del|--delete|-D)
+  if [ $# -eq 0 ] ; then
+    stderr "No release specified"
+    exit 1
+  fi
+  rc=0
+  for rel in "$@"
+  do
+    # Check if the release exists
+    chk=$(gh release list | awk -vrel="$rel" '$1 == rel { print $1; }')
+    if [ -z "$chk" ] ; then
+      stderr "$rel: not found (release list)"
+      rc=1
+      continue
+    fi
+    gh release delete $rel --yes || rc=2
+    git tag -d $rel || rc=3
+    git push --delete origin $re || rc=4
+  done
+  exit 0
+  ;;
+--test)
+  if [ -x "$checks" ] ; then
+    "$(readlink -f "$checks")" $@ || die -13 "pre-release checks failed!"
+  else
+    stderr ''
+    stderr "Skipping pre-release checks"
+    stderr "Create an executable script \"$checks\" to enable pre-release checks"
+    stderr ''
+  fi
+  exit 0
+  ;;
+esac
+
+git pull --tags # Make sure remote|local tags are in sync
 
 if [ -n "$(git tag -l $relid)" ] ; then
   echo "Tag: \"$relid\" already exists!"
@@ -141,6 +246,14 @@ else
   fi
 fi
 
+# Check for uncomitted changes
+if [ -n "$(git status --porcelain)" ] ; then
+  echo "Only run this on a clean checkout"
+  echo ''
+  git status
+  exit 3
+fi
+
 if [ -x "$checks" ] ; then
   "$(readlink -f "$checks")" $@ || die -13 "pre-release checks failed!"
 else
@@ -148,14 +261,6 @@ else
   stderr "Skipping pre-release checks"
   stderr "Create an executable script \"$checks\" to enable pre-release checks"
   stderr ''
-fi
-
-# Check for uncomitted changes
-if [ -n "$(git status --porcelain)" ] ; then
-  echo "Only run this on a clean checkout"
-  echo ''
-  git status
-  exit 3
 fi
 
 if ptag=$(git describe --abbrev=0) ; then
@@ -174,8 +279,12 @@ else
 fi
 
 printf "$vformat" "$relid" > "$vfile"
+if [ -x "$updver" ] ; then
+  "$(readlink -f "$updver")" $relid || die -98 "version updates"
+fi
+
 git add "$vfile"
-git commit -m "$relid" "$vfile"
+git commit -m "$relid"
 git tag -a "$relid" -m "$relid"
 git push
 git push --tags
